### ISSUE TITLE
Test library updates for paths/breakage

### ISSUE THREAD

**Issue by coreysnipes** [Saijin-Naib/UAVArena#16]

**Comment by Saijin-Naib** [comment]
Should be fixed with https://github.com/Saijin-Naib/UAVArena/commit/bbf765e97ccc1685ffbd31a56ec08464d4752af6

Performance is actually great, but apparently screencasting with Peek on my Intel Celeron N3450 4GB RAM netbook while using the site was too much. So the video, take with a massive truck-load of salt. It is not close to representative.
https://user-images.githubusercontent.com/19295950/223910432-c2b6104d-165d-45f5-bb94-07f48b02ab37.mp4
