### ISSUE TITLE
Verify Leaflet Plugin Compatibility With v1.9.3

### ISSUE THREAD

**Issue by Saijin-Naib** [Saijin-Naib/UAVArena#21]

**Comment by Saijin-Naib** [comment]
Side-By-Side's scrubber bar behaves a bit strangely here, but might be combination of Browser+OS.

Would like feedback from Win/Edge/Chrome/Firefox, instead of Linux/Firefox like here.

**Comment by danbjoseph** [comment]
on Chrome/macOS the scrubber bar doesn't move. the cursor icon changes but the response when dragging is panning the map. will investigate more.

**Comment by danbjoseph** [comment]
with 1f48f6a684e0ee30ca3f65b825feaf4ccaf12471 (part of PR #32) i implemented the fix described in the first post of https://github.com/digidem/leaflet-side-by-side/issues/47 and this appears to restore the expected functionality. as the fix is not yet part of the main project i'm using the local, edited, non-minified javascript file until the main project fixes this as well.
